### ISSUE TITLE
deliveryservices/id/capacity gives Internal Server Error 

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4237]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `GET` request to `/deliveryservices/{{id}}/capacity` where the deliverservice id pertains to a delivery service that was recently created and has no server assignments, the response returned is: 
```
HTTP/1.1 500 Internal Server Error
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

If there is no capacity that can be obtained it should return:
```
HTTP/1.1 200 OK
{
    "response": {
        "availablePercent": 0,
        "unavailablePercent": 0,
        "utilizedPercent": 0,
        "maintenancePercent": 0
    }
}
```

## Anything else:

`error.log` shows: `getting delivery service capacity: capacity was zero!`

**Comment by ocket8888** [comment]
Is this a regression? How did Perl handle that situation?

**Comment by ZugNZwang** [comment]
Looks like it is a regression. The Perl returned: 
```
HTTP/1.1 200 OK
{
    "response": {
        "availablePercent": 0,
        "unavailablePercent": 0,
        "utilizedPercent": 0,
        "maintenancePercent": 0
    }
}
```

**Comment by rimashah25** [comment]
@ocket8888 @mitchell852 Same issue was reported and resolved.
Issue Reported: https://github.com/apache/trafficcontrol/issues/4848
Solution: https://github.com/apache/trafficcontrol/pull/4892

This bug has been fixed and needs to be closed.

**Comment by ocket8888** [comment]
No, that was a different endpoint. That was `/cdns/capacity`, this is a similar bug in `/deliveryservices/{{ID}}/capacity`. I just looked at the code and it would seem the issue still exists.

**Comment by mitchell852** [comment]
@rimashah25 - remove all servers from ds then snapshot and see what the result of `/deliveryservices/{{ID}}/capacity` is...

**Comment by rimashah25** [comment]
Thanks @mitchell852.
