### ISSUE TITLE
Fix pkg.go.dev

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#5488]
pkg.go.dev replaces the old godoc.org Go auto-documentation site. It requires license files in certain places, or won't display documentation for libraries, for legal reasons.

It looks like it's broken for all ATC libraries: https://pkg.go.dev/github.com/apache/trafficcontrol/lib/go-tc

We should fix it. It looks like it might just be a matter of putting license files in the right places for it to detect.

Labelling bug, even though it's not our fault, because having the canonical Go docs fail really is an issue we should fix.

## I'm submitting a ...
-  bug report
- 
## Traffic Control components affected ...
-  Documentation

## Current behavior:
pkg.go.dev fails for all Go libraries in ATC.

## Expected behavior:
pkg.go.dev succeeds for all Go libraries in ATC.

## Minimal reproduction of the problem with instructions:
Go to https://pkg.go.dev/github.com/apache/trafficcontrol/lib/go-tc or any other ATC library path, observe failure.

**Comment by ocket8888** [comment]
This should be fixed by #5229 as per the discussion in #4380

**Comment by zrhoffman** [comment]
#5229 does not fix this issue. Our Godocs not displaying is a licensing issue, not a Go modules issue.

The Apache instructions for `LICENSE` and `NOTICE` files has instructions for [bundling permissively-licensed dependencies](https://infra.apache.org/licensing-howto.html#permissive-deps):
> <h3 id="permissive-deps">Bundling permissively-licensed dependencies</h3>
> <p>Bundling a dependency which is issued under one of the following licenses is straightforward, assuming that license applies uniformly to all files within the dependency:</p>
> <ul><li>BSD (without advertising clause)</li><li>MIT/X11</li></ul>
> <p>In <code>LICENSE</code>, add a <a href="http://s.apache.org/Hqj" target="_blank">pointer</a> to the dependency's license within the distribution and a short note summarizing its licensing:</p>
> <pre><code class="hljs coffeescript">This product bundles SuperWidget <span class="hljs-number">1.2</span><span class="hljs-number">.3</span>, which <span class="hljs-keyword">is</span> available under a <span class="hljs-string">"3-clause BSD"</span> license. For details, see deps<span class="hljs-regexp">/superwidget/</span>.</code></pre>
> <p>Under normal circumstances, there is no need to modify <code>NOTICE</code> to mention a bundled dependency.</p>
> <p><strong>NOTE</strong>: It's also possible to include the text of the 3rd party license within your product's <code>LICENSE</code> file. This is best reserved for short licenses. It's important to specify the version of the dependency as licenses sometimes change as product versions change.</p>

Other projects too have run into the issue of listing so many bundled dependencies in their `LICENSE` file that golang/pkgsite's use of [google/licensecheck](https://github.com/google/licensecheck) [no longer recognizes](https://github.com/golang/pkgsite/blob/5867665b19/internal/licenses/licenses.go#L43-L50) it as a valid Apache-2.0 license. Some examples:

golang/pkgsite LRE | License file
--- | ---
[mynewt.lre](https://github.com/golang/pkgsite/blob/master/internal/licenses/exceptions/mynewt.lre) and [newtmgr.lre](https://github.com/golang/pkgsite/blob/master/internal/licenses/exceptions/newtmgr.lre) | [apache/mynewt-artifact](https://github.com/apache/mynewt-artifact/blob/v0.0.15/LICENSE)
[splunk.lre](https://github.com/golang/pkgsite/blob/master/internal/licenses/exceptions/splunk.lre) | [splunk/splunk-operator](https://github.com/splunk/splunk-operator/blob/develop/LICENSE)

So, golang/pkgsite needs to have a [License Regular Expression](https://github.com/google/licensecheck/blob/main/licenses/README.md#license-regular-expressions-lres) for the ATC license, too. #5527 moves a step in this direction by normalizing the LICENSE file and adding instructions to add new entries to the bottom of the file. Note that that a common LRE between the pre-Go modules `LICENSE` file and the post-Go modules `LICENSE` file leads to coverage match percents of ~45% and ~69%, up from ~33% and ~51%, respectively, so a single LRE for both v5.0.0 and >=v5.1.0 `LICENSE` files is not a possibility, and v5.0.0 would require its own LRE if we wanted its Godocs to show up.

**Comment by ocket8888** [comment]
This can't be in 5.1, because per #4380 no changes will be made to our pkg.go.dev page without being a Go module. The Go module change will not be in 5.1.

**Comment by zrhoffman** [comment]
> This can't be in 5.1, because per #4380 no changes will be made to our pkg.go.dev page without being a Go module

While it's true that no version will replace `v1.1.3` as the default version shown for https://pkg.go.dev/github.com/apache/trafficcontrol until the project is a Go module, our non-Go module releases will still show up on https://pkg.go.dev/github.com/apache/trafficcontrol?tab=versions for all tags of the form `vX.Y.Z` (the non-Go module versions will just say `vX.Y.X+incompatible`, like [`v5.0.0+incompatible`](https://pkg.go.dev/github.com/apache/trafficcontrol@v5.0.0+incompatible)).

I backported #5527 to 5.1.x in #5610, in case we want to include it in a 5.x.x release at some point.

**Comment by zrhoffman** [comment]
Fixed in golang/pkgsite#23.

Our license is recognized in https://pkg.go.dev/github.com/apache/trafficcontrol@v5.1.1+incompatible and the docs show up for `v5.1.1` and up. We should leave #4380 open until a 5.x.x or higher version is shown as the latest version for https://pkg.go.dev/github.com/apache/trafficcontrol.
