### ISSUE TITLE
Updating a DS w/ consistent hash query params creates unrelated change log message

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5618]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
Create a new HTTP delivery service and give it one consistent hash query parameter. Now, update the delivery service. For some reason, the following API change log message is being recorded.

![image](https://user-images.githubusercontent.com/251272/110517714-70d8c100-80c8-11eb-85a1-7d0db994177c.png)

## Expected behavior:
Only if a delivery service consistent hash query parameter was deleted should that message be recorded.

## Minimal reproduction of the problem with instructions:
See current behavior.

**Comment by srijeet0406** [comment]
Should already be fixed in https://github.com/apache/trafficcontrol/pull/5410

**Comment by rawlinp** [comment]
The `Deleted N consistent hash query params` changelog message is still an issue.
